version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Vaskivskyi"
    labels:
      - "dependencies"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Vaskivskyi"
    labels:
      - "dependencies"
