exclude-contributors:
  - 'Vaskivskyi'
  - 'dependabot'
exclude-labels:
  - 'github'

categories:
  - title: "💥 Breaking Changes"
    label: "breaking"
  - title: "🚀 Features"
    label: "enhancement"
  - title: "🐞 Fixes"
    label: "bug"
  - title: "🐎 Performance"
    label: "performance"
  - title: "📖 Translation"
    label: "translation"
  - title: "🚨 Testing"
    label: "testing"
  - title: "📚 Documentation"
    label: "documentation"
  - title: "🔨 Refactoring"
    label: "refactoring"
  - title: "📦 Dependencies"
    labels: 
      - "dependencies"
      - "build"
      - "backend"

template: |
  ## Changes

  $CHANGES

