repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
        files: ^((custom-components/asusrouter|tests)/.+)?[^/]+\.(py|pyi)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=main
