name: Bug report
description: Report an issue with AsusRouter Integration
title: "[Bug] "
labels: ["bug"]
assignees:
  - vaskivskyi
body:
  - type: markdown
    attributes:
      value: >
        Please, only report bugs using this form. If you would like to submit a feature request, use the [feature request][forms] form.
        To add a new device to the compatibility list, use the [device support][forms] form.

        [forms]: https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose
  - type: input
    id: device_model
    validations:
      required: true
    attributes:
      label: Device model
      description: >
        Please, put in the full model of your device, as stated in the web panel of your router (or on the Asus webpage), e.g. `RT-AX88U`.
      placeholder: RT-
  - type: input
    id: firmware_version
    validations:
      required: true
    attributes:
      label: Firmware version
      description: >
        Please, provide the full version of the firmware, e.g. `3.0.0.4.386.5_2` or `3.0.0.4.386_48631-g10d88e5`
      placeholder: 3.0.0.4.
  - type: textarea
    id: bug_details
    validations:
      required: true
    attributes:
      label: Bug details
      description: >
        Please, describe the issue. The more details you provide, the easier it would be to understand the issue.

        Keep in mind, that the description should also be clear, so I will be able to help you with it.
