name: Device support
description: Report that your device works well with the integration
title: "[Support] "
labels: ["documentation"]
assignees:
  - vaskivskyi
body:
  - type: markdown
    attributes:
      value: >
        **This form is ONLY for reporting devices that work well with the integration.**
        
        If your device has issues or doesn't work properly, use the [bug report][forms] form instead.
        To submit a feature request, use the [feature request][forms] form.

        [forms]: https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose
  - type: input
    id: device_model
    validations:
      required: true
    attributes:
      label: Device model
      description: >
        Please, put in the full model of your device, as stated in the web panel of your router (or on the Asus webpage), e.g. `RT-AX88U`.
      placeholder: RT-
  - type: input
    id: firmware_version
    validations:
      required: true
    attributes:
      label: Firmware version
      description: >
        Please, provide the full version of the firmware, e.g. `3.0.0.4.386.5_2` or `3.0.0.4.386_48631-g10d88e5`
      placeholder: 3.0.0.4.
  - type: textarea
    id: support_details
    validations:
      required: true
    attributes:
      label: Support details
      description: >
        Please confirm that your device works well with the integration. Describe what features work correctly and any other positive feedback. 
        
        **Note: This form is only for reporting working devices. If you have issues or problems, please use the bug report form instead.**
