device_internet_access:
  target:
    entity:
      integration: asusrouter
      domain: device_tracker
  fields:
    state:
      required: true
      selector:
        select:
          translation_key: set_pc_rule
          mode: dropdown
          options:
            - "block"
            - "allow"
            - "remove"
remove_trackers:
  name: Remove device trackers
  description: This service allows removing device_tracker entities. Please, keep in mind, when run, the service will remove selected trackers from watching and will allow you to remove the entities manually.
  fields:
    entities:
      name: Entities
      description: Entities to remove
      required: true
      selector:
        entity:
          integration: asusrouter
          domain: device_tracker
          multiple: true
set_static_dhcp_lease:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: asusrouter
    mac:
      required: true
      selector:
        text:
    ip:
      required: true
      selector:
        text:
    hostname:
      required: false
      selector:
        text:
    dns:
      required: false
      selector:
        text:
remove_static_dhcp_lease:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: asusrouter
    mac:
      required: true
      selector:
        text:
reserve_current_ip:
  target:
    entity:
      integration: asusrouter
      domain: device_tracker
refresh_static_dhcp_leases:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: asusrouter
